### ISSUE TITLE
First Page

### ISSUE THREAD

**Issue by duncan-small** [mjsir911/va_voter_data_map#4]
The scraper skips the first page when going through each year, making it miss out on Presidential Elections and others.

**Comment by mjsir911** [comment]
b3e418e002a6ca9df42e93ed3743fdcf40ffd413 should fix, confirm and close.

**Comment by duncan-small** [comment]
It did not work as far as I can tell.

**Comment by duncan-small** [comment]
Using the option -t with the parameters 1-4 the first result always showed up.
python src/multiscraper.py -vvv -t 1 2>&1 | grep 'Election id' or grep '80871'
Without the option it also works now.
